#volumns:
#docker volume create --name app-postgres
#docker volume create --name app-redis

postgres:
  image: postgres:10.6
  environment:
    POSTGRES_USER: app
    POSTGRES_PASSWORD: yourpassword
  ports:
    - '5000:5432'
  volumes:
    - app-postgres:/var/lib/postgresql/data

redis:
  image: redis:5.0
  ports:
    - '6000:6379'
  volumes:
    - app-redis:/var/lib/redis/data

app:
  build: .
  links:
    - postgres
    - redis
  volumes:
    - .:/app
  ports:
    - '3000:3000'
  env_file:
    - .env.development

sidekiq:
  build: .
  command: bundle exec sidekiq -C config/sidekiq.yml
  links:
    - postgres
    - redis
  volumes:
    - .:/app
  env_file:
    - .env.development
